### PR TITLE
Used `BenchmarkStorage`, added CI script

### LINKED ISSUE #106: Use in-memory storage for benchmarks
Refactor benchmarks by moving to Maven submodule, use fast in-memory storage for benchmarks

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #106 
Used `BenchmarkStorage` in `RepoUpdateBench` and added `main` method, added action to build benchmarks

### CODE REVIEW

**Review by genryxy — COMMENTED** [review]
@olenagerasimova is it possible to start built benchmarks for one invocation and stop after that? I previously had problems when jar was built but it didn't start because of absence of dependency. Or will such a check be redundant?

**Comment by olenagerasimova** [comment]
@genryxy sorry, I do not understand what are you talking about... What do you call invocation? Benchmarks do not run here, it's just a build...

**Comment by genryxy** [comment]
@olenagerasimova yeah, I understand that it's just a build, therefore ask about start benchmark for one invocation because building does not guarantee that benchmark could run. In general, a benchmark has several iterations, each iteration includes multiple invocations.

**Comment by olenagerasimova** [comment]
@genryxy I do not think it's a good idea for github actions as we will have to set whole environment. I think that build is necessary, as we can change sdk api and benchmarks will not even build (at least we discussed this situation on Monday meeting).

**Review by genryxy — APPROVED** [review]
@olenagerasimova okay, got it

**Pull request merged**
