### PR TITLE
ci: enhance code benchmarks workflow

### PR DESCRIPTION
**Pull request by genryxy**
Part of artipie/artipie#431
Remove some lines for copying results because it is included into `make` step. Use custom actions for running benchmarks and creating PR

### CODE REVIEW

**Review by g4s8 — APPROVED** [review]
@genryxy thanks

**Comment by genryxy** [comment]
@g4s8 could you please check. I used custom actions

**Comment by genryxy** [comment]
@g4s8 could you please check

**Review by g4s8 — APPROVED** [review]
@genryxy thanks

**Comment by genryxy** [comment]
@g4s8 could you please merge

**Pull request merged**
